version: "3.8"
services:
  app:
    container_name: fastify-testing
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://winverse:winverse@postgres:5432/fastify?schema=public
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: winverse
      POSTGRES_PASSWORD: winverse
      POSTGRES_DB: fastify
  